# Generated by Django 5.1.3 on 2024-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunny',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bunny',
            name='photo',
            field=models.URLField(),
        ),
    ]
