# Generated by Django 5.1.3 on 2024-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnies', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_of_people', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
